/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `curb_group` (
  `group_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目组ID',
  `name` VARCHAR(32) NOT NULL COMMENT '项目组名称',
  `url` VARCHAR(128) NOT NULL COMMENT '项目组网址',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`group_id`) USING BTREE,
  UNIQUE KEY `uk_name` (`name`) USING BTREE,
  UNIQUE KEY `uk_url` (`url`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目组信息表';

CREATE TABLE IF NOT EXISTS `curb_group_secret` (
  `group_id` INT UNSIGNED NOT NULL COMMENT '项目组ID',
  `secret` VARCHAR(64) NOT NULL COMMENT '项目组密钥',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`group_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目组密钥表';

CREATE TABLE `curb_app` (
  `app_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '应用ID',
  `group_id` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '所属项目组ID',
  `name` VARCHAR(32) NOT NULL COMMENT '应用名称',
  `url` VARCHAR(128) NOT NULL COMMENT '应用网址',
  `state` TINYINT UNSIGNED NOT NULL COMMENT '状态：0:未知;1:已启用;2:已禁用',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`app_id`) USING BTREE,
  UNIQUE KEY `uk_name` (`name`) USING BTREE,
  UNIQUE KEY `uk_url` (`url`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用信息表';

CREATE TABLE IF NOT EXISTS `curb_app_secret` (
  `app_id` INT UNSIGNED NOT NULL COMMENT '应用ID',
  `secret` VARCHAR(64) NOT NULL COMMENT '应用密钥',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`app_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用密钥表';

CREATE TABLE IF NOT EXISTS `curb_app_menu` (
  `app_id` INT UNSIGNED NOT NULL COMMENT '应用ID',
  `version` INT UNSIGNED NOT NULL COMMENT '菜单数据版本号',
  `user_id` INT UNSIGNED NOT NULL COMMENT '保存用户ID',
  `menu` text NOT NULL COMMENT '菜单数据',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`app_id`, `version`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用菜单数据表';

CREATE TABLE IF NOT EXISTS `curb_page` (
  `page_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '页面ID',
  `app_id` INT UNSIGNED NOT NULL COMMENT '所属应用ID',
  `path` VARCHAR(255) NOT NULL COMMENT '页面路径',
  `name` VARCHAR(32) NOT NULL COMMENT '页面名称',
  `type` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '页面类型(0:amis页面;1:普通HTML页面)',
  `access_level` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '访问控制等级(0:允许匿名访问;1:允许登录用户访问;2:允许有权限用户访问)',
  `sign` VARCHAR(255) NOT NULL COMMENT '权限标识',
  `version` INT UNSIGNED NOT NULL COMMENT '当前版本号',
  `state` TINYINT UNSIGNED NOT NULL COMMENT '状态：0:未知;1:已启用;2:已禁用',
  `create_user_id` INT UNSIGNED NOT NULL COMMENT '创建用户ID',
  `update_user_id` INT UNSIGNED NOT NULL COMMENT '最后更新用户ID',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`page_id`) USING BTREE,
  UNIQUE KEY `uk_app_id_path` (`app_id`,`path`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='页面信息表';

CREATE TABLE IF NOT EXISTS `curb_page_body` (
  `page_id` INT UNSIGNED NOT NULL COMMENT '页面ID',
  `version` INT UNSIGNED NOT NULL COMMENT '页面版本号',
  `user_id` INT UNSIGNED NOT NULL COMMENT '保存用户ID',
  `body` text NOT NULL COMMENT '页面内容',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`page_id`, `version`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='页面信息表';

CREATE TABLE IF NOT EXISTS `curb_permission` (
  `perm_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权限ID',
  `app_id` INT UNSIGNED NOT NULL COMMENT '应用ID',
  `sign` VARCHAR(255) NOT NULL COMMENT '权限标识',
  `name` VARCHAR(32) NOT NULL COMMENT '权限名称',
  `description` VARCHAR(255) NOT NULL COMMENT '权限描述',
  `state` TINYINT UNSIGNED NOT NULL COMMENT '状态：0:未知;1:已启用;2:已禁用',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`perm_id`) USING BTREE,
  UNIQUE KEY `uk_app_id_sign` (`app_id`,`sign`) USING BTREE,
  KEY `uk_app_id_name` (`app_id`,`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限信息表';

CREATE TABLE IF NOT EXISTS `curb_role` (
  `role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `group_id` INT UNSIGNED NOT NULL COMMENT '所属项目组ID',
  `sign` VARCHAR(255) NOT NULL COMMENT '标识',
  `name` VARCHAR(32) NOT NULL COMMENT '角色名',
  `description` VARCHAR(255) NOT NULL COMMENT '角色描述',
  `state` TINYINT UNSIGNED NOT NULL COMMENT '状态：0:未知;1:已启用;2:已禁用',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`role_id`) USING BTREE,
  UNIQUE KEY `uk_group_id_sign` (`group_id`,`sign`) USING BTREE,
  UNIQUE KEY `uk_group_id_name` (`group_id`,`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色信息表';

CREATE TABLE IF NOT EXISTS `curb_role_permission` (
  `role_id` INT UNSIGNED NOT NULL COMMENT '角色ID',
  `perm_id` INT UNSIGNED NOT NULL COMMENT '权限ID',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`role_id`,`perm_id`) USING BTREE,
  UNIQUE KEY `uk_perm_id_role_id` (`perm_id`, `role_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色与权限关系表';

CREATE TABLE IF NOT EXISTS `curb_user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` VARCHAR(32) NOT NULL COMMENT '登录用户名',
  `name` VARCHAR(32) NOT NULL COMMENT '用户姓名',
  `type` TINYINT UNSIGNED NOT NULL COMMENT '用户类型(0:内部用户, 1:外部用户)',
  `state` TINYINT UNSIGNED NOT NULL COMMENT '状态：0:未知;1:已启用;2:已禁用',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `uk_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户信息表';

CREATE TABLE IF NOT EXISTS `curb_user_role` (
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `role_id` INT UNSIGNED NOT NULL COMMENT '角色ID',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`user_id`,`role_id`),
  UNIQUE KEY `uk_role_id_user_id` (`role_id`,`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户与角色关系表';

CREATE TABLE IF NOT EXISTS `curb_user_role_system` (
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `group_id` INT UNSIGNED NOT NULL COMMENT '项目组',
  `role_id` INT UNSIGNED NOT NULL COMMENT '角色ID',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`user_id`,`group_id`,`role_id`) USING BTREE,
  UNIQUE KEY `UK_ROLE_USER` (`role_id`,`group_id`,`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户与系统角色关系表';

CREATE TABLE IF NOT EXISTS `curb_op_log` (
  `log_id` bigint UNSIGNED NOT NULL COMMENT '操作日志ID',
  `event_time` DATETIME NOT NULL COMMENT '操作发生时间',
  `username` VARCHAR(32) NOT NULL COMMENT '操作者用户名',
  `ip` VARCHAR(32) NOT NULL COMMENT '操作者IP',
  `group_id` INT UNSIGNED NOT NULL COMMENT '项目组ID',
  `app_id` INT UNSIGNED NOT NULL COMMENT '应用ID',
  `method` VARCHAR(10) NOT NULL COMMENT '操作的HTTP方法',
  `url` VARCHAR(500) NOT NULL COMMENT '操作的URL',
  `cost` INT NOT NULL COMMENT '操作耗时(单位毫秒)',
  `state` TINYINT UNSIGNED NOT NULL COMMENT '访问控制检查结果',
  `result` VARCHAR(255) NOT NULL COMMENT '操作结果数据',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '数据创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '最近更新时间',
  PRIMARY KEY (`log_id`) USING BTREE,
  KEY `idx_username_event_time_group_id_app_id` (`username`, `event_time`, `group_id`, `app_id`) USING BTREE,
  KEY `idx_event_time_group_id_app_id_username` (`event_time`, `group_id`, `app_id`, `username`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户操作日志表';

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
