server:
  port: 8000
#  servlet.session:
#    tracking-modes:

spring:
  application:
    name: curb-client-starter-demo

  output:
    ansi:
      enabled: always

  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  level:
    root: debug
    org.mybatis: info
    org.apache.tomcat: info
    org.hibernate: info
    org.apache.catalina: info
    org.springframework: debug

curb:
  enabled: true
  client:
    server: 127.0.0.1:8080
    appid: 1
    secret: 7f279a4d-bfbd-11ed-a782-0242ac110002
  reverse-proxy: # 客户端反向代理功能配置，该功能可将部分路径请求代理到logincenter服务端，在客户端实现logincenter的其他功能（应用权限管理、LEGO等）
    enabled: false # 该配置默认关闭，需要显式开启， 注意，该配置优先级默认是最低的，controller和静态资源的路径, 优先于该配置，请设置spring.mvc.static-path-pattern，或者考虑调整优先级(LoginCenterClientProxyRequestHandler.setOrder)
    url-mappings: /** # 开启后将拦截url-mappings匹配的请求路径转发。该配置默认为 /** 即所有请求(未被其他handlermapping匹配到)。
  test-mode:
    enabled: true
    user:
      userId: 13
      username: t1
      name: T1

